### ISSUE TITLE
Is it still able to use? Can we support OneDrive API?

### ISSUE THREAD

**Issue by hsluoyz** [open-networks/go-msgraph#1]

**Comment by TerraTalpi** [comment]
Hello @hsluoyz, yes, this can still be used. We are using this API connection in production for one of our programs. The OneDrive API is part of the msgraph API according to this:
- https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http
- https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0

So yes, it OneDrive API can be supported and based on the already done work it should be easy to implement it and add structs for the OneDrive Objects. Pull requests to add support for that are welcome 👍

**Comment by hsluoyz** [comment]
Thanks for the answer. BTW do we support the daemon app auth way?

**Comment by TerraTalpi** [comment]
I am sorry, I dont know what you mean. I only implemented the one way with TenantID, ApplicationID and ClientSecret, linked at the example how to get the credentials. No other authentication mechanism is implemented so far. Can you send me a link to the msgraph docs for this authentication method?

**Comment by hsluoyz** [comment]
This way: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview

**Comment by hsluoyz** [comment]
I tried and it works. Thanks!
