### ISSUE TITLE
Question: New Version?

### ISSUE THREAD

**Issue by WTIGER001** [open-networks/go-msgraph#14]
Can you please tag a version 0.1.1 with the latest changes?

**Comment by TerraTalpi** [comment]
Hello @WTIGER001,
I want to release v0.2.0 because your changes bring a new feature - custom endpoints and create a user. Before I release the new version, I want to add Unit Tests for the newly created code and make some changes to unify the code with the rest. I plan to finish it that week.

**Comment by WTIGER001** [comment]
Ok. Thanks.. I appreciate the response.

**Comment by TerraTalpi** [comment]
Hello @WTIGER001, I have now release v0.2.0 - you can reference that version in go modules. I plan to release a v0.2.1 soon with added unit tests for UpdateUser, but that's just for completeness. Function-wise nothing is planned to change.
