### ISSUE TITLE
Please add 'jobTitle' to user struct

### ISSUE THREAD

**Issue by WTIGER001** [open-networks/go-msgraph#27]
**Is your feature request related to a problem? Please describe.**
Please add the jobTitle to the user struct

**Describe the solution you'd like**
Please add the jobTitle to the user struct

**Describe alternatives you've considered**
N/A

**Additional context**
Just need to be able to read and write the jobTitle

**Comment by TerraTalpi** [comment]
Hello @WTIGER001 , I have now implemented this change in commit 2ff8288f61a7dc593e849a5fbfd258cb083c7dc3

**Comment by WTIGER001** [comment]
Thanks!
