### ISSUE TITLE
ListMembers function not working as expected. Returning empty msgraph.Users list

### ISSUE THREAD

**Issue by somachris** [open-networks/go-msgraph#6]
When using the below code, groups returns with all of the expected information, but groupMembers returns with only the object ID and all other fields are empty. I can confirm in azure portal that the object IDs are correct, and we get one empty object per group member, but no data. 

```
	graphClient, err := msgraph.NewGraphClient(tenantID, clientID, clientSecret)
	if err != nil {
		fmt.Println("Credentials are probably wrong or system time is not synced: ", err)
	}

	groups, err := graphClient.ListGroups()
	if err != nil {
		fmt.Println("Error", err)
	}

	groupMembers, err:= groups[0].ListMembers()
	if err != nil {
		fmt.Println("Error", err)
	}

	json.NewEncoder(res).Encode(groupMembers)
```

The response from ListMembers() looks like this: 

`[
{"id":"99f2f82b-08f8-4054-b4c8-458698aaa861","businessPhones":[],"displayName":"","givenName":"","mail":"","mobilePhone":"","preferredLanguage":"","surname":"","userPrincipalName":""},{"id":"cb53abcc-47e3-4843-b9c4-5f93f247f1ca","businessPhones":[],"displayName":"","givenName":"","mail":"","mobilePhone":"","preferredLanguage":"","surname":"","userPrincipalName":""}
]`

How can we return a list of members for a group using msgraph?

**Comment by TerraTalpi** [comment]
Hello @somachris, sorry for the delay, but I have now tried your code above. Everything works from my side, and I get valid result, returning all the users that are in that particular group. I cannot find any issue with that. Maybe the group[0] on your side is an empty group? On my side, `BusinessPhones`, `DisplayName`, `Mail` etc. are all filled with data. Can you somehow provide more info from your side, maybe check the groups or after `graphClient.ListGroups()` use `groups.GetByDisplayName("valid-group-name")` and list the members of that group?

**Comment by somachris** [comment]
@TerraTalpi It turned out to be a permissions issue in the azure portal. Everything is working great now.

**Comment by TerraTalpi** [comment]
@somachris ok thanks for the update, I'll close this issue then.
